categoryreport:
    pattern:  /
    defaults: { _controller: "SirOtBundle:CategoryReport:index" }

categoryreport_show:
    pattern:  /{id}/show
    defaults: { _controller: "SirOtBundle:CategoryReport:show" }

categoryreport_new:
    pattern:  /new
    defaults: { _controller: "SirOtBundle:CategoryReport:new" }

categoryreport_create:
    pattern:  /create
    defaults: { _controller: "SirOtBundle:CategoryReport:create" }
    requirements: { _method: post }

categoryreport_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SirOtBundle:CategoryReport:edit" }

categoryreport_update:
    pattern:  /{id}/update
    defaults: { _controller: "SirOtBundle:CategoryReport:update" }
    requirements: { _method: post|put }

categoryreport_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SirOtBundle:CategoryReport:delete" }
    requirements: { _method: post|delete }
