expensekind:
    pattern:  /
    defaults: { _controller: "SirOtBundle:Expensekind:index" }

expensekind_show:
    pattern:  /{id}/show
    defaults: { _controller: "SirOtBundle:Expensekind:show" }

expensekind_new:
    pattern:  /new
    defaults: { _controller: "SirOtBundle:Expensekind:new" }

expensekind_create:
    pattern:  /create
    defaults: { _controller: "SirOtBundle:Expensekind:create" }
    requirements: { _method: post }

expensekind_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SirOtBundle:Expensekind:edit" }

expensekind_update:
    pattern:  /{id}/update
    defaults: { _controller: "SirOtBundle:Expensekind:update" }
    requirements: { _method: post|put }

expensekind_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SirOtBundle:Expensekind:delete" }
    requirements: { _method: post|delete }
