profession:
    pattern:  /
    defaults: { _controller: "SirOtBundle:Profession:index" }

profession_show:
    pattern:  /{id}/show
    defaults: { _controller: "SirOtBundle:Profession:show" }

profession_new:
    pattern:  /new
    defaults: { _controller: "SirOtBundle:Profession:new" }

profession_create:
    pattern:  /create
    defaults: { _controller: "SirOtBundle:Profession:create" }
    requirements: { _method: post }

profession_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SirOtBundle:Profession:edit" }

profession_update:
    pattern:  /{id}/update
    defaults: { _controller: "SirOtBundle:Profession:update" }
    requirements: { _method: post|put }

profession_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SirOtBundle:Profession:delete" }
    requirements: { _method: post|delete }
