technicalexaminationkind:
    pattern:  /
    defaults: { _controller: "SirOtBundle:Technicalexaminationkind:index" }

technicalexaminationkind_show:
    pattern:  /{id}/show
    defaults: { _controller: "SirOtBundle:Technicalexaminationkind:show" }

technicalexaminationkind_new:
    pattern:  /new
    defaults: { _controller: "SirOtBundle:Technicalexaminationkind:new" }

technicalexaminationkind_create:
    pattern:  /create
    defaults: { _controller: "SirOtBundle:Technicalexaminationkind:create" }
    requirements: { _method: post }

technicalexaminationkind_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SirOtBundle:Technicalexaminationkind:edit" }

technicalexaminationkind_update:
    pattern:  /{id}/update
    defaults: { _controller: "SirOtBundle:Technicalexaminationkind:update" }
    requirements: { _method: post|put }

technicalexaminationkind_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SirOtBundle:Technicalexaminationkind:delete" }
    requirements: { _method: post|delete }
