traumacause:
    pattern:  /
    defaults: { _controller: "SirOtBundle:Traumacause:index" }

traumacause_show:
    pattern:  /{id}/show
    defaults: { _controller: "SirOtBundle:Traumacause:show" }

traumacause_new:
    pattern:  /new
    defaults: { _controller: "SirOtBundle:Traumacause:new" }

traumacause_create:
    pattern:  /create
    defaults: { _controller: "SirOtBundle:Traumacause:create" }
    requirements: { _method: post }

traumacause_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SirOtBundle:Traumacause:edit" }

traumacause_update:
    pattern:  /{id}/update
    defaults: { _controller: "SirOtBundle:Traumacause:update" }
    requirements: { _method: post|put }

traumacause_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SirOtBundle:Traumacause:delete" }
    requirements: { _method: post|delete }
