SirOtBundle_medical:
        resource: "@SirOtBundle/Resources/config/routing/medical.yml"
        prefix:   /medical

SirOtBundle_traumakind:
        resource: "@SirOtBundle/Resources/config/routing/traumakind.yml"
        prefix:   /traumakind

SirOtBundle_traumacause:
        resource: "@SirOtBundle/Resources/config/routing/traumacause.yml"
        prefix:   /traumacause

SirOtBundle_employee:
        resource: "@SirOtBundle/Resources/config/routing/employee.yml"
        prefix:   /employee

SirOtBundle_equipmentsubgroup:
        resource: "@SirOtBundle/Resources/config/routing/equipmentsubgroup.yml"
        prefix:   /equipmentsubgroup

SirOtBundle_equipmentgroup:
        resource: "@SirOtBundle/Resources/config/routing/equipmentgroup.yml"
        prefix:   /equipmentgroup

SirOtBundle_medicalkind: #вид медосмотра
        resource: "@SirOtBundle/Resources/config/routing/medicalkind.yml"
        prefix:   /medicalkind

SirOtBundle_professionkind:
        resource: "@SirOtBundle/Resources/config/routing/professionkind.yml"
        prefix:   /professionkind

SirOtBundle_profession:
        resource: "@SirOtBundle/Resources/config/routing/profession.yml"
        prefix:   /profession

SirOtBundle_technicalexamination:
        resource: "@SirOtBundle/Resources/config/routing/technicalexamination.yml"
        prefix:   /technicalexamination

SirOtBundle_equipment:
        resource: "@SirOtBundle/Resources/config/routing/equipment.yml"
        prefix:   /equipment

SirOtBundle_trauma:
        resource: "@SirOtBundle/Resources/config/routing/trauma.yml"
        prefix:   /trauma

SirOtBundle_medicaltype: #характер медосмотра
        resource: "@SirOtBundle/Resources/config/routing/medicaltype.yml"
        prefix:   /medicaltype

SirOtBundle_user:
        resource: "@SirOtBundle/Resources/config/routing/user.yml"
        prefix:   /user

SirOtBundle_subdivision:
        resource: "@SirOtBundle/Resources/config/routing/subdivision.yml"
        prefix:   /subdivision

SirOtBundle_enterprise:
        resource: "@SirOtBundle/Resources/config/routing/enterprise.yml"
        prefix:   /enterprise

sir_ot:
    pattern:  /
    defaults: { _controller: SirOtBundle:Default:index }