#parameters:
#    sir_ot.example.class: Sir\OtBundle\SirOtBundle
#
services:
  sir_ot:
    class: Sir\OtBundle\SirOtBundle
    arguments: ["@security.context"]

  request:
    class:        Symfony\Component\HttpFoundation\Request

  sir.twig.extension:
    class: Sir\OtBundle\Twig\Extension\SirOtExtension
    arguments:  [@request]
    tags:
      - { name: 'twig.extension' }

