equipmentgroup_index:
    path: /
    defaults:
        _controller: MainBundle:Equipmentgroup:index

equipmentgroup_show:
    path: /{id}/show
    defaults:
        _controller: MainBundle:Equipmentgroup:show

equipmentgroup_list:
    path: /list
    defaults:
        _controller: MainBundle:Equipmentgroup:list

equipmentgroup_new:
    path: /new
    defaults:
        _controller: MainBundle:Equipmentgroup:edit

equipmentgroup_edit:
    path: /{id}/edit
    defaults:
        _controller: MainBundle:Equipmentgroup:edit

equipmentgroup_remove:
    path: /{id}/remove
    defaults:
        _controller: MainBundle:Equipmentgroup:remove