medicaltype_index:
    path: /
    defaults:
        _controller: MainBundle:Medicaltype:index

medicaltype_show:
    path: /{id}/show
    defaults:
        _controller: MainBundle:Medicaltype:show

medicaltype_list:
    path: /list
    defaults:
        _controller: MainBundle:Medicaltype:list

medicaltype_new:
    path: /new
    defaults:
        _controller: MainBundle:Medicaltype:edit

medicaltype_edit:
    path: /{id}/edit
    defaults:
        _controller: MainBundle:Medicaltype:edit

medicaltype_remove:
    path: /{id}/remove
    defaults:
        _controller: MainBundle:Medicaltype:remove