medicalkind_index:
    path: /
    defaults:
        _controller: MainBundle:Medicalkind:index

medicalkind_show:
    path: /{id}/show
    defaults:
        _controller: MainBundle:Medicalkind:show

medicalkind_list:
    path: /list
    defaults:
        _controller: MainBundle:Medicalkind:list

medicalkind_new:
    path: /new
    defaults:
        _controller: MainBundle:Medicalkind:edit

medicalkind_edit:
    path: /{id}/edit
    defaults:
        _controller: MainBundle:Medicalkind:edit

medicalkind_remove:
    path: /{id}/remove
    defaults:
        _controller: MainBundle:Medicalkind:remove