medical_index:
    path: /
    defaults:
        _controller: MainBundle:Medical:index

medical_show:
    path: /{id}/show
    defaults:
        _controller: MainBundle:Medical:show

medical_list:
    path: /list
    defaults:
        _controller: MainBundle:Medical:list

medical_new:
    path: /new
    defaults:
        _controller: MainBundle:Medical:edit

medical_edit:
    path: /{id}/edit
    defaults:
        _controller: MainBundle:Medical:edit

medical_remove:
    path: /{id}/remove
    defaults:
        _controller: MainBundle:Medical:remove