report:
    pattern:  /
    defaults: { _controller: "MainBundle:Report:index" }

report_show:
    pattern:  /{id}/show
    defaults: { _controller: "MainBundle:Report:show" }

report_new:
    pattern:  /new
    defaults: { _controller: "MainBundle:Report:new" }

report_create:
    pattern:  /create
    defaults: { _controller: "MainBundle:Report:create" }
    requirements: { _method: post }

report_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MainBundle:Report:edit" }

report_update:
    pattern:  /{id}/update
    defaults: { _controller: "MainBundle:Report:update" }
    requirements: { _method: post|put }

report_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MainBundle:Report:delete" }
    requirements: { _method: post|delete }
