technicalexaminationtype_index:
    path: /
    defaults:
        _controller: MainBundle:Technicalexaminationtype:index

technicalexaminationtype_show:
    path: /{id}/show
    defaults:
        _controller: MainBundle:Technicalexaminationtype:show

technicalexaminationtype_list:
    path: /list
    defaults:
        _controller: MainBundle:Technicalexaminationtype:list

technicalexaminationtype_new:
    path: /new
    defaults:
        _controller: MainBundle:Technicalexaminationtype:edit

technicalexaminationtype_edit:
    path: /{id}/edit
    defaults:
        _controller: MainBundle:Technicalexaminationtype:edit

technicalexaminationtype_remove:
    path: /{id}/remove
    defaults:
        _controller: MainBundle:Technicalexaminationtype:remove